import Foundation
import Capacitor
import WidgetKit

// Bridge that hands the web app's numbers to the home screen widget. The web
// side calls sync({ data }) with a JSON string; we drop it into the shared App
// Group so the widget extension can read it, then ask WidgetKit to redraw.
//
// Registration (SPM Capacitor): this is a local plugin, exactly like
// ICloudBackupPlugin. In this project's SPM setup the CAP_PLUGIN macro in the
// .m file is NOT enough on its own — the class name ALSO has to be listed in
// `packageClassList` inside ios/App/App/capacitor.config.json, or the bridge
// reports "SaverWidget plugin is not implemented on ios" and sync() silently
// no-ops. That file is gitignored and REGENERATED by every `npx cap sync` /
// `npx cap copy`, which wipes the two hand-added local plugins. The npm
// `cap:copy`/`cap:sync` scripts run scripts/patch-ios-plugins.mjs to re-add
// them automatically; if you ever run the raw `npx cap` command, re-run that
// patch (or `npm run cap:patch`) before building.
@objc(SaverWidgetPlugin)
public class SaverWidgetPlugin: CAPPlugin {
    // Must match the App Group id added to BOTH the App target and the widget
    // target in Xcode (Signing & Capabilities).
    private let appGroup = "group.com.savertrack.app"
    private let key = "widgetData"

    @objc func sync(_ call: CAPPluginCall) {
        let json = call.getString("data") ?? "{}"
        if let defaults = UserDefaults(suiteName: appGroup) {
            defaults.set(json, forKey: key)
        }
        if #available(iOS 14.0, *) {
            WidgetCenter.shared.reloadAllTimelines()
        }
        call.resolve()
    }
}
